apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-workspace-integration
  labels:
    app: google-workspace-integration
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: google-workspace-integration
  template:
    metadata:
      name: google-workspace-integration
      labels:
        app: google-workspace-integration
    spec:
      containers:
        - name: google-workspace-integration
          image: vatusa/google-workspace-integration
          imagePullPolicy: IfNotPresent
          command: ["/app/core"]
          envFrom:
            - secretRef:
                name: discord-bot
      restartPolicy: Always
