package config

var FacilityDomains = map[string][]string{
	Albuquerque:  {},
	Anchorage:    {},
	Atlanta:      {},
	Boston:       {},
	Chicago:      {},
	Cleveland:    {},
	Denver:       {"zdvartcc.org"},
	FortWorth:    {"zfwartcc.net"},
	Honolulu:     {},
	Houston:      {},
	Indianapolis: {},
	Jacksonville: {},
	KansasCity:   {},
	LosAngeles:   {},
	Memphis:      {},
	Miami:        {"zmaartcc.net"},
	Minneapolis:  {},
	NewYork:      {},
	Oakland:      {},
	SaltLake:     {"zlcartcc.org"},
	Seattle:      {},
	Washington:   {"vzdc.org"},
}
