name: Build Image

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image (bot)
        run: docker build . --file Dockerfile --tag image --target app
